all:
  children:
    ovpn2:
      hosts:
        ras:
          ansible_host: 192.168.19.30
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
    ovpn1:
      hosts:
        server:
          ansible_host: 192.168.19.10
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant
        client:
          ansible_host: 192.168.19.20
          ansible_port: 22
          ansible_user: vagrant
          ansible_password: vagrant

